server:
  port: 8054

spring:
  application:
    name: chaincharts-api
  datasource:
    username: user
    password: password
    url:  jdbc:postgresql://localhost:5432/chaincharts
  flyway:
    url: jdbc:postgresql://localhost:5432/chaincharts
    user: user
    password: password

